use crate::domain::{CodeQueryKind, CodeRetrievalRequest};

use super::code_query_path_ranking::{
    path_looks_like_test_or_benchmark, query_mentions_test_or_benchmark,
};

const HYBRID_TEST_CHUNK_PENALTY: f64 = -3.75;
const HYBRID_GENERATED_CHUNK_PENALTY: f64 = -3.0;
const HYBRID_TYPE_SURFACE_CHUNK_BONUS: f64 = 5.25;

pub(super) fn hybrid_chunk_path_adjustment(
    base_score: f64,
    query: &str,
    content: &str,
    path: &str,
    request: &CodeRetrievalRequest,
) -> f64 {
    if base_score <= 0.0 || request.code_query_kind != CodeQueryKind::Hybrid {
        return 0.0;
    }

    let mut penalty = 0.0;
    if !query_mentions_test_or_benchmark(query) && path_looks_like_test_or_benchmark(path) {
        penalty += HYBRID_TEST_CHUNK_PENALTY;
    }
    if !query_requests_generated_chunk(query, content) && content_looks_generated(content) {
        penalty += HYBRID_GENERATED_CHUNK_PENALTY;
    }
    if query_mentions_type_surface(query) && compact_type_surface_body(content) {
        penalty += HYBRID_TYPE_SURFACE_CHUNK_BONUS;
    }

    penalty
}

fn query_requests_generated_chunk(query: &str, content: &str) -> bool {
    let query_terms = query_terms(query);
    query_terms.iter().any(|term| {
        matches!(
            term.as_str(),
            "autogenerated" | "codegen" | "generated" | "generator"
        )
    }) || generated_source_terms(content).iter().any(|source_term| {
        query_terms
            .iter()
            .any(|query_term| query_term == source_term)
    })
}

fn query_terms(query: &str) -> Vec<String> {
    query
        .split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
        .filter(|term| !term.is_empty())
        .map(str::to_ascii_lowercase)
        .collect()
}

fn generated_source_terms(content: &str) -> Vec<String> {
    content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(4)
        .filter_map(|line| {
            line.to_ascii_lowercase()
                .split_once("generated by ")
                .map(|(_, source)| source.to_owned())
        })
        .flat_map(|source| {
            source
                .split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
                .filter(|term| term.len() >= 4)
                .filter(|term| !matches!(*term, "edit" | "generated"))
                .map(str::to_owned)
                .collect::<Vec<_>>()
        })
        .collect()
}

fn content_looks_generated(content: &str) -> bool {
    content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(4)
        .any(|line| {
            let lower = line.to_ascii_lowercase();
            lower.contains("code generated")
                || lower.contains("do not edit")
                || lower.contains("autogenerated")
        })
}

fn query_mentions_type_surface(query: &str) -> bool {
    let terms = query
        .split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
        .filter(|term| !term.is_empty())
        .map(str::to_ascii_lowercase)
        .collect::<Vec<_>>();
    terms.iter().any(|term| term == "type")
        && terms
            .iter()
            .any(|term| matches!(term.as_str(), "component" | "metadata"))
}

fn compact_type_surface_body(content: &str) -> bool {
    let nonblank_lines = content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(9)
        .count();
    if nonblank_lines == 0 || nonblank_lines > 8 {
        return false;
    }
    let lower = content.to_ascii_lowercase();
    lower.contains(" type") || lower.contains(".type") || lower.contains("type()")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{CodeRepositorySelector, FreshnessPolicy};

    #[test]
    fn hybrid_chunk_path_adjustment_demotes_unrequested_test_and_generated_chunks() {
        let request = request("sink.NewFactory EmitBatches metric_sink");

        assert_eq!(
            hybrid_chunk_path_adjustment(
                12.0,
                &request.query,
                "func TestFactory(t *testing.T) {}",
                "connectors/metricsink/metricsink_test.go",
                &request,
            ),
            HYBRID_TEST_CHUNK_PENALTY
        );
        assert_eq!(
            hybrid_chunk_path_adjustment(
                12.0,
                &request.query,
                "// Code generated by schema compiler. DO NOT EDIT.",
                "connectors/metricsink/internal/generated_status.go",
                &request,
            ),
            HYBRID_GENERATED_CHUNK_PENALTY
        );
    }

    #[test]
    fn hybrid_chunk_path_adjustment_preserves_requested_surfaces() {
        let test_request = request("db bench std function compression");
        let generated_request = request("generated stage table row");

        assert_eq!(
            hybrid_chunk_path_adjustment(
                12.0,
                &test_request.query,
                "benchmark body",
                "benchmarks/db_bench.cc",
                &test_request,
            ),
            0.0
        );
        assert_eq!(
            hybrid_chunk_path_adjustment(
                12.0,
                &generated_request.query,
                "// Code generated by schema compiler. DO NOT EDIT.",
                "src/generated_table.c",
                &generated_request,
            ),
            0.0
        );
    }

    #[test]
    fn hybrid_chunk_path_adjustment_preserves_indexed_generated_source_intent() {
        let request = request("schema compiler status table");

        assert_eq!(
            hybrid_chunk_path_adjustment(
                12.0,
                &request.query,
                "// Code generated by schema compiler. DO NOT EDIT.",
                "src/generated_status.go",
                &request,
            ),
            0.0
        );
    }

    #[test]
    fn hybrid_chunk_path_adjustment_boosts_compact_type_surface_body() {
        let request = request("metricsink plugin component Type MustNewType metric_sink");

        assert_eq!(
            hybrid_chunk_path_adjustment(
                8.0,
                &request.query,
                "func (PluginType) Type() component.Type {\n\treturn metadata.Type\n}",
                "connectors/metricsink/metricsink.go",
                &request,
            ),
            HYBRID_TYPE_SURFACE_CHUNK_BONUS
        );
    }

    fn request(query: &str) -> CodeRetrievalRequest {
        CodeRetrievalRequest::new(
            query,
            CodeRepositorySelector::new("repo", "HEAD", Vec::new(), vec!["go".to_owned()])
                .expect("selector should validate"),
            CodeQueryKind::Hybrid,
            10,
            FreshnessPolicy::AllowStale,
        )
        .expect("request should validate")
    }
}
