use std::path::PathBuf;

use super::{
    categories::CategorySet,
    jobs::Jobs,
    mode::{Mode, Strategy},
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Config {
    pub mode: Mode,
    pub strategy: Strategy,
    pub workspace: PathBuf,
    pub yolo: bool,
    pub model: Option<String>,
    pub codex_reasoning_effort: String,
    pub codex_profile: Option<String>,
    pub codex_path: Option<String>,
    pub codex_timeout_seconds: u64,
    pub command_timeout_seconds: u64,
    pub profile: String,
    pub max_iterations: Option<usize>,
    pub stop_after_accepted: Option<usize>,
    pub sleep_seconds: u64,
    pub commit_message: Option<String>,
    pub dry_run_codex: bool,
    pub keep_workdirs: bool,
    pub use_current_candidate: bool,
    pub fail_fast: bool,
    pub jobs: Jobs,
    pub repo_jobs: Jobs,
    pub query_jobs: Jobs,
    pub categories: Option<CategorySet>,
    pub max_wall_clock_hours: u64,
    pub explore_timeout_seconds: u64,
    pub macro_explore_timeout_seconds: u64,
    pub max_explore_attempts_per_cycle: usize,
    pub max_consecutive_empty_candidates: usize,
    pub max_consecutive_promotion_failures: usize,
    pub macro_after_competitive_failures: usize,
    pub macro_after_empty_candidates: usize,
    pub cycle_sleep_seconds: u64,
    pub cooldown_after_accept_seconds: u64,
    pub cooldown_after_timeout_seconds: u64,
    pub deep_check_interval_accepts: usize,
    pub deep_check_interval_hours: u64,
    pub research_topic: String,
    pub research_slug: String,
    pub research_date: String,
}
