use super::*;
use crate::domain::{CodeRepositorySelector, FreshnessPolicy};

#[test]
fn hybrid_chunk_path_adjustment_demotes_unrequested_test_and_generated_chunks() {
    let request = request("sink.NewFactory EmitBatches metric_sink");

    assert_eq!(
        hybrid_chunk_path_adjustment(
            12.0,
            &request.query,
            "func TestFactory(t *testing.T) {}",
            "connectors/metricsink/metricsink_test.go",
            &request,
        ),
        HYBRID_TEST_CHUNK_PENALTY
    );
    assert_eq!(
        hybrid_chunk_path_adjustment(
            12.0,
            &request.query,
            "// Code generated by schema compiler. DO NOT EDIT.",
            "connectors/metricsink/internal/generated_status.go",
            &request,
        ),
        HYBRID_GENERATED_CHUNK_PENALTY
    );
}

#[test]
fn hybrid_chunk_path_adjustment_preserves_low_scoring_sole_chunk_hits() {
    let request = request("sink.NewFactory EmitBatches metric_sink");
    let base_score = 1.0;

    let adjustment = hybrid_chunk_path_adjustment(
        base_score,
        &request.query,
        "func TestFactory(t *testing.T) {}",
        "connectors/metricsink/metricsink_test.go",
        &request,
    );

    assert!((base_score + adjustment - MIN_DEMOTED_HYBRID_CHUNK_SCORE).abs() < f64::EPSILON);
}

#[test]
fn hybrid_chunk_path_adjustment_demotes_generated_path_symbol_chunks() {
    let request = request("sink.NewFactory EmitBatches metric_sink");

    assert_eq!(
        hybrid_chunk_path_adjustment(
            12.0,
            &request.query,
            "pub fn generated_status() -> Status { Status::Ready }",
            "src/generated/status.rs",
            &request,
        ),
        HYBRID_GENERATED_CHUNK_PENALTY
    );
}

#[test]
fn hybrid_chunk_path_adjustment_preserves_requested_surfaces() {
    let test_request = request("db bench std function compression");
    let generated_request = request("generated stage table row");

    assert_eq!(
        hybrid_chunk_path_adjustment(
            12.0,
            &test_request.query,
            "benchmark body",
            "benchmarks/db_bench.cc",
            &test_request,
        ),
        0.0
    );
    assert_eq!(
        hybrid_chunk_path_adjustment(
            12.0,
            &generated_request.query,
            "// Code generated by schema compiler. DO NOT EDIT.",
            "src/generated_table.c",
            &generated_request,
        ),
        0.0
    );
}

#[test]
fn hybrid_chunk_path_adjustment_preserves_indexed_generated_source_intent() {
    let request = request("schema compiler status table");

    assert_eq!(
        hybrid_chunk_path_adjustment(
            12.0,
            &request.query,
            "// Code generated by schema compiler. DO NOT EDIT.",
            "src/generated_status.go",
            &request,
        ),
        0.0
    );
}

#[test]
fn hybrid_chunk_path_adjustment_boosts_compact_type_surface_body() {
    let request = request("metricsink plugin component Type MustNewType metric_sink");

    assert_eq!(
        hybrid_chunk_path_adjustment(
            8.0,
            &request.query,
            "func (PluginType) Type() component.Type {\n\treturn metadata.Type\n}",
            "connectors/metricsink/metricsink.go",
            &request,
        ),
        HYBRID_TYPE_SURFACE_CHUNK_BONUS
    );
}

fn request(query: &str) -> CodeRetrievalRequest {
    CodeRetrievalRequest::new(
        query,
        CodeRepositorySelector::new("repo", "HEAD", Vec::new(), vec!["go".to_owned()])
            .expect("selector should validate"),
        CodeQueryKind::Hybrid,
        10,
        FreshnessPolicy::AllowStale,
    )
    .expect("request should validate")
}
