mod adopted_documentation;
mod candidate_evaluation;
mod dispatch;
mod documentation_gate;
mod generation_iteration;
mod loop_control;
mod manual_evaluation;
mod output;
mod pacing;
mod persistence;
mod report_metadata;
mod run_identity;

pub(crate) use adopted_documentation::write_adopted_optimization_document;
pub(crate) use candidate_evaluation::evaluate_candidate_for_patch;
pub(crate) use dispatch::run;
pub(crate) use documentation_gate::apply_candidate_documentation_gate;
pub(crate) use output::{number, print_score};
pub(crate) use pacing::sleep_seconds;
pub(crate) use persistence::{PersistInput, persist_scored_run_with_score};
pub(crate) use run_identity::{new_layer_run_id, unix_timestamp};
