use crate::domain::{CodeQueryKind, CodeRetrievalRequest};

use super::code_query_path_ranking::{
    path_looks_like_test_or_benchmark, query_mentions_test_or_benchmark,
};

const HYBRID_TEST_CHUNK_PENALTY: f64 = -3.75;
const HYBRID_GENERATED_CHUNK_PENALTY: f64 = -3.0;
const HYBRID_TYPE_SURFACE_CHUNK_BONUS: f64 = 5.25;
const MIN_DEMOTED_HYBRID_CHUNK_SCORE: f64 = 0.01;

pub(super) fn hybrid_chunk_path_adjustment(
    base_score: f64,
    query: &str,
    content: &str,
    path: &str,
    request: &CodeRetrievalRequest,
) -> f64 {
    if base_score <= 0.0 || request.code_query_kind != CodeQueryKind::Hybrid {
        return 0.0;
    }

    let mut penalty = 0.0;
    if !query_mentions_test_or_benchmark(query) && path_looks_like_test_or_benchmark(path) {
        penalty += HYBRID_TEST_CHUNK_PENALTY;
    }
    if !query_requests_generated_chunk(query, content)
        && (content_looks_generated(content) || path_looks_generated(path))
    {
        penalty += HYBRID_GENERATED_CHUNK_PENALTY;
    }
    if query_mentions_type_surface(query) && compact_type_surface_body(content) {
        penalty += HYBRID_TYPE_SURFACE_CHUNK_BONUS;
    }

    if penalty < 0.0 && base_score + penalty <= 0.0 {
        MIN_DEMOTED_HYBRID_CHUNK_SCORE - base_score
    } else {
        penalty
    }
}

fn query_requests_generated_chunk(query: &str, content: &str) -> bool {
    let query_terms = query_terms(query);
    query_terms.iter().any(|term| {
        matches!(
            term.as_str(),
            "autogenerated" | "codegen" | "generated" | "generator"
        )
    }) || generated_source_terms(content).iter().any(|source_term| {
        query_terms
            .iter()
            .any(|query_term| query_term == source_term)
    })
}

fn query_terms(query: &str) -> Vec<String> {
    query
        .split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
        .filter(|term| !term.is_empty())
        .map(str::to_ascii_lowercase)
        .collect()
}

fn generated_source_terms(content: &str) -> Vec<String> {
    content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(4)
        .filter_map(|line| {
            line.to_ascii_lowercase()
                .split_once("generated by ")
                .map(|(_, source)| source.to_owned())
        })
        .flat_map(|source| {
            source
                .split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
                .filter(|term| term.len() >= 4)
                .filter(|term| !matches!(*term, "edit" | "generated"))
                .map(str::to_owned)
                .collect::<Vec<_>>()
        })
        .collect()
}

fn content_looks_generated(content: &str) -> bool {
    content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(4)
        .any(|line| {
            let lower = line.to_ascii_lowercase();
            lower.contains("code generated")
                || lower.contains("do not edit")
                || lower.contains("autogenerated")
        })
}

fn path_looks_generated(path: &str) -> bool {
    path.split(|character: char| {
        matches!(character, '/' | '\\' | '-' | '_' | '.') || character.is_ascii_whitespace()
    })
    .filter(|segment| !segment.is_empty())
    .any(|segment| {
        matches!(
            segment.to_ascii_lowercase().as_str(),
            "autogen" | "autogenerated" | "codegen" | "generated"
        )
    })
}

fn query_mentions_type_surface(query: &str) -> bool {
    let terms = query
        .split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
        .filter(|term| !term.is_empty())
        .map(str::to_ascii_lowercase)
        .collect::<Vec<_>>();
    terms.iter().any(|term| term == "type")
        && terms
            .iter()
            .any(|term| matches!(term.as_str(), "component" | "metadata"))
}

fn compact_type_surface_body(content: &str) -> bool {
    let nonblank_lines = content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .take(9)
        .count();
    if nonblank_lines == 0 || nonblank_lines > 8 {
        return false;
    }
    let lower = content.to_ascii_lowercase();
    lower.contains(" type") || lower.contains(".type") || lower.contains("type()")
}

#[cfg(test)]
#[path = "chunk_path_tests.rs"]
mod tests;
