//! Repository query, context, feature-flag, impact, view, and software command contracts.

use super::super::{CliCommandSpec, CommandEffect, arg, command_syntax, opt};

pub(in crate::interfaces::cli::spec) fn repo_query() -> CliCommandSpec {
    command!(
        &["repo", "query"],
        "relay-knowledge repo query <alias> --query <text> [--kind <kind>] [--ref <ref>] [--path <filter>] [--language <id>] [--freshness <policy>] [--exclude-generated] [--limit <n>]",
        "Retrieve code symbols, references, and chunks from a repository index.",
        "code.repo.query",
        CommandEffect::ReadOnly,
        &[arg(
            "alias",
            true,
            false,
            "Registered repository alias.",
            None,
            &[],
        )],
        &[
            opt(
                "--query",
                Some("text"),
                true,
                false,
                "Code search text; multiple unflagged words after --query are joined.",
                None,
                &[],
            ),
            opt(
                "--kind",
                Some("kind"),
                false,
                false,
                "Code retrieval mode.",
                Some("hybrid"),
                &[
                    "hybrid",
                    "symbol",
                    "definition",
                    "references",
                    "callers",
                    "callees",
                    "imports",
                    "sbom",
                ],
            ),
            opt(
                "--ref",
                Some("ref"),
                false,
                false,
                "Indexed Git ref or worktree selector.",
                Some("HEAD"),
                &[],
            ),
            opt(
                "--path",
                Some("filter"),
                false,
                true,
                "Restricts query to indexed path prefix.",
                None,
                &[],
            ),
            opt(
                "--language",
                Some("id"),
                false,
                true,
                "Restricts query to language id.",
                None,
                &[],
            ),
            opt(
                "--freshness",
                Some("policy"),
                false,
                false,
                "Controls index freshness.",
                Some("allow-stale"),
                &["allow-stale", "wait-until-fresh", "graph-only"],
            ),
            opt(
                "--limit",
                Some("n"),
                false,
                false,
                "Maximum result count requested from the API.",
                Some("10"),
                &[],
            ),
            opt(
                "--exclude-generated",
                None,
                false,
                false,
                "Exclude generated files from query results.",
                None,
                &[],
            ),
        ],
        &["relay-knowledge repo query core --query retry_policy --kind definition --format json"],
        &[
            "The meaning of --kind is command-local; do not reuse index or worker kind values here.",
            "Generated files remain indexed for freshness and statistics; --exclude-generated only filters retrieval results.",
        ],
    )
}

pub(in crate::interfaces::cli::spec) fn repo_context() -> CliCommandSpec {
    command!(
        &["repo", "context"],
        "relay-knowledge repo context <alias> --query <text> [--ref <ref>] [--path <filter>] [--language <id>] [--freshness <policy>] [--limit <n>] [--max-context-bytes <n>] [--no-code] [--exclude-generated]",
        "Build a one-call codegraph context pack for coding agents.",
        "code.repo.context",
        CommandEffect::ReadOnly,
        &[arg(
            "alias",
            true,
            false,
            "Registered repository alias.",
            None,
            &[],
        )],
        &[
            opt(
                "--query",
                Some("text"),
                true,
                false,
                "Context request text; multiple unflagged words after --query are joined.",
                None,
                &[],
            ),
            opt(
                "--ref",
                Some("ref"),
                false,
                false,
                "Indexed Git ref or worktree selector.",
                Some("HEAD"),
                &[],
            ),
            opt(
                "--path",
                Some("filter"),
                false,
                true,
                "Restricts context to indexed path prefix.",
                None,
                &[],
            ),
            opt(
                "--language",
                Some("id"),
                false,
                true,
                "Restricts context to language id.",
                None,
                &[],
            ),
            opt(
                "--freshness",
                Some("policy"),
                false,
                false,
                "Controls index freshness.",
                Some("allow-stale"),
                &["allow-stale", "wait-until-fresh", "graph-only"],
            ),
            opt(
                "--limit",
                Some("n"),
                false,
                false,
                "Maximum entry, related-symbol, and graph-path count per group.",
                Some("8"),
                &[],
            ),
            opt(
                "--max-context-bytes",
                Some("n"),
                false,
                false,
                "Maximum serialized context pack size.",
                Some("65536"),
                &[],
            ),
            opt(
                "--no-code",
                None,
                false,
                false,
                "Omit code excerpts while keeping provenance and graph evidence.",
                None,
                &[],
            ),
            opt(
                "--exclude-generated",
                None,
                false,
                false,
                "Exclude generated files from context evidence.",
                None,
                &[],
            ),
        ],
        &[
            "relay-knowledge repo context core --query \"retry_policy callers imports\" --format json",
        ],
        &[
            "The command orchestrates existing code graph queries and does not trigger repository indexing or refresh.",
            "JSON includes entry_points, related_symbols, graph_paths, impact_hints, code_excerpts, freshness, budget, and truncation diagnostics.",
        ],
    )
}

pub(in crate::interfaces::cli::spec) fn repo_feature_flags() -> CliCommandSpec {
    command!(
        &["repo", "feature-flags"],
        "relay-knowledge repo feature-flags <alias> [--query <text>] [--ref <ref>] [--path <filter>] [--language <id>] [--freshness <policy>] [--limit <n>]",
        "List configuration-driven feature flags and code relationships from a repository index.",
        "code.repo.feature_flags",
        CommandEffect::ReadOnly,
        &[arg(
            "alias",
            true,
            false,
            "Registered repository alias.",
            None,
            &[],
        )],
        &[
            opt(
                "--query",
                Some("text"),
                false,
                false,
                "Optional filter over feature flag name, config key, path, or excerpt.",
                None,
                &[],
            ),
            opt(
                "--ref",
                Some("ref"),
                false,
                false,
                "Indexed Git ref or worktree selector.",
                Some("HEAD"),
                &[],
            ),
            opt(
                "--path",
                Some("filter"),
                false,
                true,
                "Restricts query to indexed path prefix.",
                None,
                &[],
            ),
            opt(
                "--language",
                Some("id"),
                false,
                true,
                "Restricts query to language id.",
                None,
                &[],
            ),
            opt(
                "--freshness",
                Some("policy"),
                false,
                false,
                "Controls index freshness.",
                Some("allow-stale"),
                &["allow-stale", "wait-until-fresh", "graph-only"],
            ),
            opt(
                "--limit",
                Some("n"),
                false,
                false,
                "Maximum feature flag groups requested from the API.",
                Some("50"),
                &[],
            ),
        ],
        &["relay-knowledge repo feature-flags core --query checkout --format json"],
        &[
            "Feature flags are indexed facts; this command does not scan the repository at query time."
        ],
    )
}

pub(in crate::interfaces::cli::spec) fn repo_impact() -> CliCommandSpec {
    command!(
        &["repo", "impact"],
        "relay-knowledge repo impact <alias> --base <ref> --head <ref> [--limit <n>]",
        "Analyze code impact between two refs.",
        "code.repo.impact",
        CommandEffect::ReadOnly,
        &[arg(
            "alias",
            true,
            false,
            "Registered repository alias.",
            None,
            &[],
        )],
        &[
            opt(
                "--base",
                Some("ref"),
                true,
                false,
                "Base ref for diff analysis.",
                None,
                &[],
            ),
            opt(
                "--head",
                Some("ref"),
                true,
                false,
                "Head ref for diff analysis.",
                None,
                &[],
            ),
            opt(
                "--limit",
                Some("n"),
                false,
                false,
                "Maximum impact result count.",
                Some("100"),
                &[],
            ),
        ],
        &["relay-knowledge repo impact core --base main --head HEAD --format json"],
        &[],
    )
}

pub(in crate::interfaces::cli::spec) fn repo_view() -> CliCommandSpec {
    command!(
        &["repo", "view"],
        "relay-knowledge repo view <alias> [--kind architecture-layers|business-domains|dependency-tour|process-flow|affected-scope] [--ref <ref>] [--path <filter>] [--language <id>] [--freshness <policy>] [--limit <n>] [--changed-path <path>]",
        "Read an evidence-backed codebase understanding view derived from indexed graph facts.",
        "code.repo.view",
        CommandEffect::ReadOnly,
        &[arg(
            "alias",
            true,
            false,
            "Registered repository alias.",
            None,
            &[],
        )],
        &[
            opt(
                "--kind",
                Some("kind"),
                false,
                false,
                "View family to derive.",
                Some("architecture-layers"),
                &[
                    "architecture-layers",
                    "business-domains",
                    "dependency-tour",
                    "process-flow",
                    "affected-scope",
                ],
            ),
            opt(
                "--ref",
                Some("ref"),
                false,
                false,
                "Indexed Git ref or worktree selector.",
                Some("HEAD"),
                &[],
            ),
            opt(
                "--path",
                Some("filter"),
                false,
                true,
                "Restricts the selected repository scope by path prefix.",
                None,
                &[],
            ),
            opt(
                "--language",
                Some("id"),
                false,
                true,
                "Restricts the selected repository scope by language id.",
                None,
                &[],
            ),
            opt(
                "--freshness",
                Some("policy"),
                false,
                false,
                "Controls code graph freshness.",
                Some("allow-stale"),
                &["allow-stale", "wait-until-fresh", "graph-only"],
            ),
            opt(
                "--limit",
                Some("n"),
                false,
                false,
                "Maximum node, edge, and section count requested from the API.",
                Some("20"),
                &[],
            ),
            opt(
                "--changed-path",
                Some("path"),
                false,
                true,
                "Changed path used by affected-scope deterministic v1.",
                None,
                &[],
            ),
        ],
        &[
            "relay-knowledge repo view core --kind dependency-tour --freshness wait-until-fresh --format json",
            "relay-knowledge repo view core --kind affected-scope --changed-path src/lib.rs --format json",
        ],
        &[
            "Views are derived read models from committed code graph facts; narrative sections are not persisted as graph facts.",
            "`affected-scope` requires one or more `--changed-path` values in deterministic v1.",
        ],
    )
}

pub(in crate::interfaces::cli::spec) fn repo_software() -> CliCommandSpec {
    command!(
        &["repo", "software"],
        "relay-knowledge repo software <alias> [--ref <ref>] [--kind dependencies|sdks|files|topics|relationships|build|iac|design|all] [--freshness <policy>] [--limit <n>]",
        "Read repository-scoped software dependency, SDK/API, file, topic, relationship, build, IaC, and design facts.",
        "code.repo.software",
        CommandEffect::ReadOnly,
        &[arg(
            "alias",
            true,
            false,
            "Registered repository alias.",
            None,
            &[],
        )],
        &[
            opt(
                "--ref",
                Some("ref"),
                false,
                false,
                "Indexed Git ref or worktree selector.",
                Some("HEAD"),
                &[],
            ),
            opt(
                "--kind",
                Some("kind"),
                false,
                false,
                "Software global projection slice.",
                Some("all"),
                &[
                    "dependencies",
                    "sdks",
                    "files",
                    "topics",
                    "relationships",
                    "build",
                    "iac",
                    "design",
                    "all",
                ],
            ),
            opt(
                "--freshness",
                Some("policy"),
                false,
                false,
                "Controls projection freshness.",
                Some("allow-stale"),
                &["allow-stale", "wait-until-fresh", "graph-only"],
            ),
            opt(
                "--limit",
                Some("n"),
                false,
                false,
                "Maximum rows per returned projection slice.",
                Some("100"),
                &[],
            ),
        ],
        &["relay-knowledge repo software core --kind all --format json"],
        &[
            "The projection is built from authorized repository index facts: dependency manifests, lockfiles, unresolved import/include targets, build manifests, IaC files, and design documentation."
        ],
    )
}

#[cfg(test)]
#[path = "mod_tests.rs"]
mod tests;
